### ISSUE TITLE
Add a milestone for 2.2.0 version

### ISSUE THREAD

**Issue by TheMeinerLP** [CloudNetService/CloudNet-v2#194]
Add a milestone for the 2.2.0
Some things that would need a revision and improvements for the 2.2.0+:
- [x] Rework database backend to fix Out of Memory bug -> #189 
- [ ] GameServer class, split big content methods into smaller -> #191 
- [x] Change some class uses from tarek-functional into java functional
- [x] Change use from [CollectionWrapper](https://github.com/CloudNetService/CloudNet/blob/master/cloudnet-lib/src/main/java/de/dytanic/cloudnet/lib/utility/CollectionWrapper.java), into lambadas/stream api
- [x] Change use from [MapWrapper](https://github.com/CloudNetService/CloudNet/blob/master/cloudnet-lib/src/main/java/de/dytanic/cloudnet/lib/utility/MapWrapper.java), into lambadas/stream api
- [x] Remove some [Trio](https://github.com/CloudNetService/CloudNet/blob/master/cloudnet-lib/src/main/java/de/dytanic/cloudnet/lib/utility/Trio.java), [Quad](https://github.com/CloudNetService/CloudNet/blob/master/cloudnet-lib/src/main/java/de/dytanic/cloudnet/lib/utility/Quad.java), [Return](https://github.com/CloudNetService/CloudNet/blob/master/cloudnet-lib/src/main/java/de/dytanic/cloudnet/lib/utility/Return.java), [Catcher](https://github.com/CloudNetService/CloudNet/blob/master/cloudnet-lib/src/main/java/de/dytanic/cloudnet/lib/utility/Catcher.java) and [Acceptable](https://github.com/CloudNetService/CloudNet/blob/master/cloudnet-lib/src/main/java/de/dytanic/cloudnet/lib/utility/Acceptable.java) classes and replace it with entity/model classes and rightful code
- [ ] Remove and replace the [Document](https://github.com/CloudNetService/CloudNet/blob/master/cloudnet-lib/src/main/java/de/dytanic/cloudnet/lib/utility/document/Document.java) class with JsonElement/JsonObject*
- [ ] Add some more Statistics*

_* this is optional_

Some more tasks coming in the future

Finished and in progress tasks in the Project/Milestone and under this issue

**Comment by GiantTreeLP** [comment]
Milestone is created and the mentioned issues and PRs are assigned to it.
